"""This module contains unit tests for the dna.py module.

The tests verify the correct functionality of the DNA animation
generated by the animate_dna function.
The animation involves replacing placeholders with
random DNA bases, and the tests ensure that these bases (A, T, C, G)
appear in the output as expected"""

import sys
from unittest.mock import patch
from io import StringIO
from dna import animate_dna


def test_animate_dna():
    """This test ensures that the animate_dna function
    correctly generates the DNA animation output."""
    with patch('time.sleep', return_value=None), patch('random.choice', return_value='A'):
        # Capturing printed output using StringIO
        captured_output = StringIO()
        sys.stdout = captured_output
        animate_dna(0.0)  # We will stop after one iteration

        # Check if the output contains the DNA animation
        assert 'A' in captured_output.getvalue()
        assert 'T' in captured_output.getvalue()
        sys.stdout = sys.__stdout__  # Reset redirect
